version: '3'
services:
  solr:
    container_name: solr
    depends_on:
    image: solr
    ports:
      - 8983
    volumes:
    links:
  populator:
    image: scaledmarkets/recommender_tfidf-pop
    links:
      - solr
  searcher:
    image: scaledmarkets/recommender_tfidf-search
    links:
      - solr
  