version: '3'
services:
  mysql:
    container_name: ....
    depends_on:
    image: ....
    ports:
      - ....
    volumes:
    links:
  recommender:
    image: ${UserSimRecImageName}
    links:
      - mysql
  