# Configurations pertaining to the build environment.
export SOLR_HOME := ~/Library/solr-7.0.0
export MAHOUT_HOME := ~/Library/apache-mahout-distribution-0.13.0
export jar_dir := /Transient/Recommenders
export maxerrs = 5
CUCUMBER_HOME:=$(HOME)/Library/Cucumber
